# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Docker image
        run: |
          docker pull nginx
          docker images
          ls

      - name: Download Artifact
        run: |
          wget https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz
          tar -xzvf tmas-cli_Linux_x86_64.tar.gz

      - name: Scan Artifact
        env:
          TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
        run: ./tmas scan docker:nginx:latest - -VMS --saveSBOM > results.json
        
      - name: Upload Json as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-json
          path: results.json   
